using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Services;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace WebApplication1
{
    public partial class BulkBookingUpload : System.Web.UI.Page
    {
        private string connectionString = ConfigurationManager.ConnectionStrings["HotelDB"].ConnectionString;

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                // Set EPPlus license context
                ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            }
        }

        //[WebMethod]
        //public static object GenerateTemplate()
        //{
        //    try
        //    {
        //        // Template will be generated by a handler
        //        return new { success = true };
        //    }
        //    catch (Exception ex)
        //    {
        //        return new { success = false, message = ex.Message };
        //    }
        //}

        protected void btnUpload_Click(object sender, EventArgs e)
        {
            try
            {
                // Validate inputs
                if (string.IsNullOrWhiteSpace(txtAgentId.Text))
                {
                    ShowError("Agent ID is required");
                    return;
                }

                if (string.IsNullOrWhiteSpace(txtLocation.Text))
                {
                    ShowError("Location is required");
                    return;
                }

                if (!fileUpload.HasFile)
                {
                    ShowError("Please select an Excel file");
                    return;
                }

                // Validate file extension
                string fileExtension = Path.GetExtension(fileUpload.FileName).ToLower();
                if (fileExtension != ".xlsx" && fileExtension != ".xls")
                {
                    ShowError("Invalid file format. Please upload .xlsx or .xls file");
                    return;
                }

                // Process the Excel file
                ProcessExcelFile();
            }
            catch (Exception ex)
            {
                ShowError("Error processing file: " + ex.Message);
            }
        }

        private void ProcessExcelFile()
        {
            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;

            List<string> validationErrors = new List<string>();
            List<BookingRecord> bookings = new List<BookingRecord>();

            using (var package = new ExcelPackage(fileUpload.FileContent))
            {
                ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
                int rowCount = worksheet.Dimension.Rows;

                // Start from row 2 (skip header)
                for (int row = 2; row <= rowCount; row++)
                {
                    try
                    {
                        var booking = new BookingRecord
                        {
                            GuestName = GetCellValue(worksheet, row, 1),
                            GuestEmail = GetCellValue(worksheet, row, 2),
                            GuestPhone = GetCellValue(worksheet, row, 3),
                            HotelCode = GetCellValue(worksheet, row, 4),
                            RoomType = GetCellValue(worksheet, row, 5),
                            CheckInDate = ParseDate(GetCellValue(worksheet, row, 6)),
                            CheckOutDate = ParseDate(GetCellValue(worksheet, row, 7)),
                            NumberOfGuests = ParseInt(GetCellValue(worksheet, row, 8)),
                            SpecialRequests = GetCellValue(worksheet, row, 9),
                            AgentId = txtAgentId.Text.Trim(),
                            AgentLocation = txtLocation.Text.Trim(),
                            UploadedDate = DateTime.Now
                        };

                        // Validate booking
                        var errors = ValidateBooking(booking, row);
                        if (errors.Count > 0)
                        {
                            validationErrors.AddRange(errors);
                        }
                        else
                        {
                            bookings.Add(booking);
                        }
                    }
                    catch (Exception ex)
                    {
                        validationErrors.Add($"Row {row}: Error - {ex.Message}");
                    }
                }
            }

            // If there are validation errors, show them
            if (validationErrors.Count > 0)
            {
                ShowValidationErrors(validationErrors);
                return;
            }

            // Insert bookings into database
            int successCount = BulkInsertBookings(bookings);

            // Show success message
            string script = $@"
                <script>
                    showResults(true, 'Upload Successful!', [
                        'Total records processed: {bookings.Count}',
                        'Successfully inserted: {successCount}',
                        'Agent: {txtAgentId.Text}',
                        'Location: {txtLocation.Text}'
                    ]);
                </script>";
            ClientScript.RegisterStartupScript(this.GetType(), "ShowResults", script);
        }

        private List<string> ValidateBooking(BookingRecord booking, int row)
        {
            List<string> errors = new List<string>();

            if (string.IsNullOrWhiteSpace(booking.GuestName))
                errors.Add($"Row {row}: Guest Name is required");

            if (string.IsNullOrWhiteSpace(booking.GuestEmail))
                errors.Add($"Row {row}: Guest Email is required");
            else if (!IsValidEmail(booking.GuestEmail))
                errors.Add($"Row {row}: Invalid email format");

            if (string.IsNullOrWhiteSpace(booking.GuestPhone))
                errors.Add($"Row {row}: Guest Phone is required");

            if (string.IsNullOrWhiteSpace(booking.HotelCode))
                errors.Add($"Row {row}: Hotel Code is required");

            if (string.IsNullOrWhiteSpace(booking.RoomType))
                errors.Add($"Row {row}: Room Type is required");

            if (booking.CheckInDate == DateTime.MinValue)
                errors.Add($"Row {row}: Invalid Check-In Date");

            if (booking.CheckOutDate == DateTime.MinValue)
                errors.Add($"Row {row}: Invalid Check-Out Date");

            if (booking.CheckInDate >= booking.CheckOutDate)
                errors.Add($"Row {row}: Check-Out Date must be after Check-In Date");

            if (booking.CheckInDate < DateTime.Today)
                errors.Add($"Row {row}: Check-In Date cannot be in the past");

            if (booking.NumberOfGuests <= 0)
                errors.Add($"Row {row}: Number of Guests must be greater than 0");

            return errors;
        }

        private int BulkInsertBookings(List<BookingRecord> bookings)
        {
            int successCount = 0;

            try
            {
                using (SqlConnection conn = new SqlConnection(connectionString))
                {
                    conn.Open();

                    // Create a DataTable for bulk insert
                    DataTable dt = new DataTable();
                    dt.Columns.Add("BookingId", typeof(string));
                    dt.Columns.Add("GuestName", typeof(string));
                    dt.Columns.Add("GuestEmail", typeof(string));
                    dt.Columns.Add("GuestPhone", typeof(string));
                    dt.Columns.Add("HotelCode", typeof(string));
                    dt.Columns.Add("RoomType", typeof(string));
                    dt.Columns.Add("CheckInDate", typeof(DateTime));
                    dt.Columns.Add("CheckOutDate", typeof(DateTime));
                    dt.Columns.Add("NumberOfGuests", typeof(int));
                    dt.Columns.Add("SpecialRequests", typeof(string));
                    dt.Columns.Add("AgentId", typeof(string));
                    dt.Columns.Add("AgentLocation", typeof(string));
                    dt.Columns.Add("BookingStatus", typeof(string));
                    dt.Columns.Add("UploadedDate", typeof(DateTime));

                    foreach (var booking in bookings)
                    {
                        dt.Rows.Add(
                            GenerateBookingId(),
                            booking.GuestName,
                            booking.GuestEmail,
                            booking.GuestPhone,
                            booking.HotelCode,
                            booking.RoomType,
                            booking.CheckInDate,
                            booking.CheckOutDate,
                            booking.NumberOfGuests,
                            booking.SpecialRequests ?? "",
                            booking.AgentId,
                            booking.AgentLocation,
                            "Pending",
                            booking.UploadedDate
                        );
                    }

                    // Use SqlBulkCopy for efficient bulk insert
                    using (SqlBulkCopy bulkCopy = new SqlBulkCopy(conn))
                    {
                        bulkCopy.DestinationTableName = "HotelBookings";
                        bulkCopy.BatchSize = 100;

                        // Map columns
                        bulkCopy.ColumnMappings.Add("BookingId", "BookingId");
                        bulkCopy.ColumnMappings.Add("GuestName", "GuestName");
                        bulkCopy.ColumnMappings.Add("GuestEmail", "GuestEmail");
                        bulkCopy.ColumnMappings.Add("GuestPhone", "GuestPhone");
                        bulkCopy.ColumnMappings.Add("HotelCode", "HotelCode");
                        bulkCopy.ColumnMappings.Add("RoomType", "RoomType");
                        bulkCopy.ColumnMappings.Add("CheckInDate", "CheckInDate");
                        bulkCopy.ColumnMappings.Add("CheckOutDate", "CheckOutDate");
                        bulkCopy.ColumnMappings.Add("NumberOfGuests", "NumberOfGuests");
                        bulkCopy.ColumnMappings.Add("SpecialRequests", "SpecialRequests");
                        bulkCopy.ColumnMappings.Add("AgentId", "AgentId");
                        bulkCopy.ColumnMappings.Add("AgentLocation", "AgentLocation");
                        bulkCopy.ColumnMappings.Add("BookingStatus", "BookingStatus");
                        bulkCopy.ColumnMappings.Add("UploadedDate", "UploadedDate");

                        bulkCopy.WriteToServer(dt);
                        successCount = dt.Rows.Count;
                    }
                }
            }
            catch (SqlException sqlEx)
            {
                // Log the SQL error and rethrow with more context
                throw new Exception($"Database error during bulk insert: {sqlEx.Message}", sqlEx);
            }
            catch (Exception ex)
            {
                throw new Exception($"Error during bulk insert: {ex.Message}", ex);
            }

            return successCount;
        }

        private string GetCellValue(ExcelWorksheet worksheet, int row, int col)
        {
            var cell = worksheet.Cells[row, col];
            return cell.Value?.ToString()?.Trim() ?? string.Empty;
        }

        private DateTime ParseDate(string dateString)
        {
            if (DateTime.TryParse(dateString, out DateTime result))
                return result;
            return DateTime.MinValue;
        }

        private int ParseInt(string intString)
        {
            if (int.TryParse(intString, out int result))
                return result;
            return 0;
        }

        private bool IsValidEmail(string email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(email);
                return addr.Address == email;
            }
            catch
            {
                return false;
            }
        }

        private string GenerateBookingId()
        {
            // Generate unique ID using timestamp + GUID
            string timestamp = DateTime.Now.ToString("yyyyMMddHHmmss");
            string uniquePart = Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper();
            return $"BK{timestamp}{uniquePart}";
        }

        private void ShowError(string message)
        {
            string script = $@"
                <script>
                    showResults(false, 'Upload Failed', ['{message}']);
                </script>";
            ClientScript.RegisterStartupScript(this.GetType(), "ShowError", script);
        }

        private void ShowValidationErrors(List<string> errors)
        {
            string errorList = string.Join("','", errors.Select(e => e.Replace("'", "\\'")));
            string script = $@"
                <script>
                    showResults(false, 'Validation Errors Found', ['{errorList}']);
                </script>";
            ClientScript.RegisterStartupScript(this.GetType(), "ShowValidationErrors", script);
        }

        private class BookingRecord
        {
            public string GuestName { get; set; }
            public string GuestEmail { get; set; }
            public string GuestPhone { get; set; }
            public string HotelCode { get; set; }
            public string RoomType { get; set; }
            public DateTime CheckInDate { get; set; }
            public DateTime CheckOutDate { get; set; }
            public int NumberOfGuests { get; set; }
            public string SpecialRequests { get; set; }
            public string AgentId { get; set; }
            public string AgentLocation { get; set; }
            public DateTime UploadedDate { get; set; }
        }
    }
}